const INIT_CONTACTS = 'INIT_CONTACTS'
const ADD_CONTACT = 'ADD_CONTACT'
const DEL_CONTACT = 'DEL_CONTACT'
const EDIT_CONTACT = 'EDIT_CONTACT'

export { INIT_CONTACTS, ADD_CONTACT, DEL_CONTACT, EDIT_CONTACT }
